### PR TITLE
Fix login signup

### LINKED ISSUE #24: Add login/Signup for the Website
Add user login and signup to the application for robust user-management.

### PR DESCRIPTION
**Pull request by haseebzaki-07**
fixes #24 

This PR fixes the issues in login and signup routes.

### CODE REVIEW

**Comment by gupta-ritik** [comment]
Add video or SS

**Comment by haseebzaki-07** [comment]
Hey @gupta-ritik The sign up route is working fine instead of returning a confirmation message it is returning a html page. 

Screenshot 2024-10-10 135132

**Comment by Maheshwari-Love** [comment]
@haseebzaki-07 please add a short clip of output...

**Comment by haseebzaki-07** [comment]
hey @Maheshwari-Love I am facing this issue the console is returning me a 200 ok status but along with some HTML page.


https://github.com/user-attachments/assets/d6be3e93-e60a-4c77-8fa9-af0fbe4d2952

**Comment by haseebzaki-07** [comment]
hey @Maheshwari-Love please provide some label to the PR

**Pull request merged**
