### PR TITLE
Added the dashboard page ui/ux at /dashboard.

### PR DESCRIPTION
**Pull request by tarunkumar2005**
Added the dashboard page ui/ux at /dashboard.

closes :- #57 

https://github.com/user-attachments/assets/e80b25bb-dc6f-4605-bf6f-b9e68ea3c279

https://github.com/user-attachments/assets/632ad693-36ec-40ea-a5ec-b81d11924be5

@gupta-ritik @Maheshwari-Love Please review this PR and merge it into main branch and assign this to me and put relavant labels such as gssoc 2024 ext, hacktoberfest and level. I think it can be level 3 as i have properly created the dashboard page ui/ux with full responsiveness and proper design with sleek ui so please level it according to the efforts and hardwork i have putted in this. Thank you.

### CODE REVIEW

**Comment by tarunkumar2005** [comment]
@Maheshwari-Love @gupta-ritik Pending PR (reminder)

**Comment by tarunkumar2005** [comment]
@Maheshwari-Love Done with the changes

**Comment by gupta-ritik** [comment]
@tarunkumar2005  add a proper video and explain how it is working after that I merge the PR and try to do this tonight

**Comment by tarunkumar2005** [comment]
@gupta-ritik I have shared the videos and it is just the ui design no functionality in it as of now we can add functionality to it according to your project preferences right as i was told by @Maheshwari-Love for now i can give a basic ui design of the dashboard but i properly designed it with responsiveness in mind and sleek ui so you can give it atleast level3 right.

**Comment by tarunkumar2005** [comment]
@gupta-ritik @Maheshwari-Love Please check the PR it is open for so long

**Comment by Maheshwari-Love** [comment]
@tarunkumar2005 The branch has employment error...

**Comment by tarunkumar2005** [comment]
@Maheshwari-Love what is that??

**Pull request closed without merging**
